### ISSUE TITLE
pew not working properly?

### ISSUE THREAD

**Issue by WuTheFWasThat** [berdario/pew#149]
If I'm understanding the usage correctly, `pew` doesn't seem to correctly activate the virtualenv for me.

See:
```
rl_sat local # pew workon rl_sat-a4OaVrmj
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

rl_sat local # which python
/usr/local/bin/python

rl_sat local # ls -lah /usr/local/bin/python
lrwxr-xr-x  1 wujeff  admin    36B Nov  3  2016 /usr/local/bin/python -> ../Cellar/python/2.7.12_2/bin/python
```

whereas

```
rl_sat local # source /Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin/activate

(rl_sat-a4OaVrmj) rl_sat local # which python
/Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin/python

rl_sat local # which python3
/Users/wujeff/.local/share/virtualenvs/rl_sat-a4OaVrmj/bin/python3
```

Not sure if it's related, but #137 is also happening to me:

```
rl_sat local # pew workon
alba-fp98i5LX  jhbot-7qvc2wnR  rl_experiments-DIi6F4TN  rl_sat-a4OaVrmj
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/Library/Python/2.7/site-packages/pew/pew.py", line 737, in pew
    return command(sys.argv[2:])
  File "/Library/Python/2.7/site-packages/pew/pew.py", line 351, in workon_cmd
    env = parse_envname(argv, lambda: lsvirtualenv(False))
  File "/Library/Python/2.7/site-packages/pew/pew.py", line 340, in parse_envname
    env = argv[0]
IndexError: list index out of range
```
(See https://github.com/kennethreitz/pipenv/issues/449 for some more context)

**Comment by WuTheFWasThat** [comment]
nevermind, it was my PATH
