### ISSUE TITLE
Problems installing python 3.5.1

### ISSUE THREAD

**Issue by dajuno** [berdario/pew#154]
I am trying to use pew to create a python 3.5.1 (the newest supported version according to `pew list_pythons`) virtual environment, but ran into problems.
I am on a HP compute server with OpenSUSE 3.16.7-53-desktop, with python3.4 installed. 
The steps are:
   
   export PATH=$HOME/.local/bin:$PATH
   export PYTHONPATH=$HOME/.local/lib/python3.4/site-packages:$PYTHONPATH
   pip3 install pew --user
   pew install 3.5.1
   pew new --python=$(pythonz locate 3.5.1) test

This produces the error:
> Running virtualenv with interpreter /Home/guests/nolte/.pythonz/pythons/CPython-3.5.1/bin/python3
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
> Traceback (most recent call last):
>   File "/Home/guests/nolte/.local/lib/python3.4/site-packages/virtualenv.py", line 16, in <module>
>     import base64
>  File "/Home/guests/nolte/.pythonz/pythons/CPython-3.5.1/lib/python3.5/base64.py", line 10, in  <module>
>     import struct
>   File "/Home/guests/nolte/.pythonz/pythons/CPython-3.5.1/lib/python3.5/struct.py", line 13, in <module>
>     from _struct import *
> ImportError: No module named '_struct'
> Error while trying to remove the /Home/guests/nolte/.local/share/virtualenvs/test2 env: 
> No such file or directory

Something (setting $PYTHONHOME?) seems to have gone wrong with the installation of python 3.5.1.

Any comments? Thanks in advance!

**Comment by berdario** [comment]
Oh :/

Sorry, not much time to properly look into into this issue, but a small note

>  python 3.5.1 (the newest supported version according to pew list_pythons) 

The latest version of Python3.5 is 3.5.4:

    > pew install 3.5.2
    WARNING: Unsupported Python version: `3.5.2`, trying with the following URL anyway: http://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz
    Downloading Python-3.5.2.tgz as /home/dario/.pythonz/dists/Python-3.5.2.tgz

The listed versions are updated manually, to be able to add the checksums. That would be done in the pythonz project, but unfortunately upstream decided to reject my patches to make it available as a library, and release it on pypi :/

Even without the checksums it's still possible to install a version (it'll just display the WARNING that I reproduced above)

Unfortunately, after pythonz rejected those patched, I haven't found a satisfying solution :/
