### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#63]
Bug reproduction:
```python
$ pew new -i python-heatclient heat-test
New python executable in heat-test/bin/python2.7
Not overwriting existing python script heat-test/bin/python (you must use heat-test/bin/python2.7)
Installing setuptools, pip, wheel...done.
Collecting python-heatclient
  Using cached python_heatclient-0.6.0-py2.py3-none-any.whl
Collecting oslo.serialization>=1.4.0 (from python-heatclient)
  Using cached oslo.serialization-1.8.0-py2.py3-none-any.whl
Collecting python-swiftclient>=2.2.0 (from python-heatclient)
  Using cached python_swiftclient-2.5.0-py2.py3-none-any.whl
Collecting oslo.i18n>=1.5.0 (from python-heatclient)
  Using cached oslo.i18n-2.3.0-py2.py3-none-any.whl
Collecting pbr<2.0,>=0.11 (from python-heatclient)
  Using cached pbr-1.4.0-py2.py3-none-any.whl
Collecting argparse (from python-heatclient)
  Using cached argparse-1.3.0-py2.py3-none-any.whl
Collecting requests>=2.5.2 (from python-heatclient)
  Using cached requests-2.7.0-py2.py3-none-any.whl
Collecting oslo.utils>=1.4.0 (from python-heatclient)
  Using cached oslo.utils-2.2.0-py2.py3-none-any.whl
Collecting iso8601>=0.1.9 (from python-heatclient)
  Using cached iso8601-0.1.10.tar.gz
Collecting six>=1.9.0 (from python-heatclient)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting PyYAML>=3.1.0 (from python-heatclient)
Collecting Babel>=1.3 (from python-heatclient)
  Using cached Babel-2.0.tar.gz
Collecting PrettyTable<0.8,>=0.7 (from python-heatclient)
  Using cached prettytable-0.7.2.tar.bz2
Collecting python-keystoneclient>=1.3.0 (from python-heatclient)
  Using cached python_keystoneclient-1.6.0-py2.py3-none-any.whl
Collecting msgpack-python>=0.4.0 (from oslo.serialization>=1.4.0->python-heatclient)
  Using cached msgpack-python-0.4.6.tar.gz
Collecting pytz>=2013.6 (from oslo.serialization>=1.4.0->python-heatclient)
  Using cached pytz-2015.4-py2.py3-none-any.whl
Collecting futures>=2.1.3 (from python-swiftclient>=2.2.0->python-heatclient)
  Using cached futures-3.0.3-py2-none-any.whl
Collecting monotonic>=0.1 (from oslo.utils>=1.4.0->python-heatclient)
  Using cached monotonic-0.3.tar.gz
Collecting netifaces>=0.10.4 (from oslo.utils>=1.4.0->python-heatclient)
  Using cached netifaces-0.10.4.tar.gz
Collecting netaddr>=0.7.12 (from oslo.utils>=1.4.0->python-heatclient)
  Using cached netaddr-0.7.15-py2.py3-none-any.whl
Collecting debtcollector>=0.3.0 (from oslo.utils>=1.4.0->python-heatclient)
  Using cached debtcollector-0.7.0-py2.py3-none-any.whl
Collecting stevedore>=1.3.0 (from python-keystoneclient>=1.3.0->python-heatclient)
  Using cached stevedore-1.7.0-py2.py3-none-any.whl
Collecting oslo.config>=1.11.0 (from python-keystoneclient>=1.3.0->python-heatclient)
  Using cached oslo.config-2.2.0-py2.py3-none-any.whl
Collecting wrapt>=1.7.0 (from debtcollector>=0.3.0->oslo.utils>=1.4.0->python-heatclient)
  Using cached wrapt-1.10.5.tar.gz
Building wheels for collected packages: iso8601, Babel, PrettyTable, msgpack-python, monotonic, netifaces, wrapt
  Running setup.py bdist_wheel for iso8601
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/3f/7c/d1/fddaaceaa3ebe55637ccc89faff444d8a6c43011fd593715a5
  Running setup.py bdist_wheel for Babel
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/15/b9/ae/1b8f9a7c0e6e06a27d0bd8e6de2f3d82292c9b00e5d0a6dd45
  Running setup.py bdist_wheel for PrettyTable
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/41/46/ec/ec86e65e50e9f4be52547a3bedd46077e7414c53d2ed0418fd
  Running setup.py bdist_wheel for msgpack-python
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/f3/97/a5/dd6e3b680de10b689464c44bc211239d1fe54bd296ff860897
  Running setup.py bdist_wheel for monotonic
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/0f/cf/72/297c6d473b3f94a80084ed52548c13bea1acf37ca543961393
  Running setup.py bdist_wheel for netifaces
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/32/42/e1/c70ed63c260bddfedf2472663153d03a17ee650b512273991d
  Running setup.py bdist_wheel for wrapt
  Stored in directory: /home/lucas_cimon/.cache/pip/wheels/1d/bd/59/f8ec76ecb9134b951bbe216327920b891acc35847024a06b50
Successfully built iso8601 Babel PrettyTable msgpack-python monotonic netifaces wrapt
Installing collected packages: pbr, msgpack-python, monotonic, pytz, Babel, six, oslo.i18n, netifaces, netaddr, wrapt, debtcollector, iso8601, oslo.utils, oslo.serialization, futures, requests, python-swiftclient, argparse, PyYAML, PrettyTable, stevedore, oslo.config, python-keystoneclient, python-heatclient
Successfully installed Babel-2.0 PrettyTable-0.7.2 PyYAML-3.11 argparse-1.3.0 debtcollector-0.7.0 futures-3.0.3 iso8601-0.1.10 monotonic-0.3 msgpack-python-0.4.6 netaddr-0.7.15 netifaces-0.10.4 oslo.config-2.2.0 oslo.i18n-2.3.0 oslo.serialization-1.8.0 oslo.utils-2.2.0 pbr-1.4.0 python-heatclient-0.6.0 python-keystoneclient-1.6.0 python-swiftclient-2.5.0 pytz-2015.4 requests-2.7.0 six-1.9.0 stevedore-1.7.0 wrapt-1.10.5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/pew/pew.py", line 490, in prevent_path_errors
    if 'VIRTUAL_ENV' in os.environ and not check_path():
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/pew/_utils.py", line 39, in check_path
    return parent(parent(which('python'))) == os.environ['VIRTUAL_ENV']
  File "/usr/lib/python2.7/posixpath.py", line 129, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

$ pew workon heat-test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/pew/pew.py", line 490, in prevent_path_errors
    if 'VIRTUAL_ENV' in os.environ and not check_path():
  File "/home/lucas_cimon/.local/lib/python2.7/site-packages/pew/_utils.py", line 39, in check_path
    return parent(parent(which('python'))) == os.environ['VIRTUAL_ENV']
  File "/usr/lib/python2.7/posixpath.py", line 129, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

I already tried to `pip2.7 install --user --upgrade pew`.

Some more info (I'm using Cygwin):
```
$ python --version
Python 2.7.9
$ pew version
0.1.14
$ uname -a
CYGWIN_NT-6.3 XXXXXXX 1.7.35(0.287/5/3) 2015-03-04 12:09 x86_64 Cygwin
```

**Comment by Lucas-C** [comment]
I don't quite get why it get into this "if" conditional in the stack trace:

    $ /usr/bin/python2.7 -c "import os; print 'VIRTUAL_ENV' in os.environ"
    False

**Comment by BartGo** [comment]
I checked with Git's Bash/command line (and Python 2.7.8, Pew 0.1.14) and I get no error so maybe it's Cygwin-specific? After
``pew new -i python-heatclient heat-test``
and the whole installation, finishing with
``Successfully installed Babel-2.0 [...] wrapt-1.10.5``
the subshell is started (but, Powershell in my setup - I don't know how to run bash from pew, I do it with vex).

**Comment by berdario** [comment]
Ok, I think I know the cause:

Which() is supposed to be executed only on Windows (to workaround a certain issue with Python and CreateProcess)... But pew has never been tested under Cygwin.

Thus, the directory separator is different, and it crashes. 

I hope this is correct (I'm reading this bug report on my phone while on the tube) 

For the other unrelated question: To run bash under pew, you can simply `pew in environment bash`

As usual, I'm quite busy... But I want to fix it... If you can put together a patch a PR is more than welcome  :) 


-- 
Sent from mobile. Please excuse my brevity.

**Comment by Lucas-C** [comment]
That's indeed the problem:

    $ python2.7 -c 'from pew._utils import which; print which("python")'
    None
    $ which python
    /usr/bin/python

I'll try to find time to look into it and open a PR before the end of the week.

**Comment by Lucas-C** [comment]
I'm going to copy Python 3.4 [shutil.which](https://hg.python.org/cpython/file/tip/Lib/shutil.py#l1072) code:

    $ python3.4 -c 'from shutil import which; print(which("python"))'
    /usr/bin/python

**Comment by berdario** [comment]
Actually, can you check if [this problem](http://bugs.python.org/issue18069) happens under cygwin as well? (it depends if it uses `CreateProcess()`, or `fork()`)

If it doesn't, the simplest solution is to change [this check](https://github.com/berdario/pew/blob/ab25e7fef4f2c8/pew/_utils.py#L43) to prevent its execution on Windows+cygwin

Otherwise, rather than copying the code in our project, it might be better to just add this dependency:

https://pypi.python.org/pypi/shutilwhich/

**Comment by Lucas-C** [comment]
I updated the pull request

+1 for using shutilwhich if you agree

**Comment by berdario** [comment]
Ok, thank you

About shutilwhich: Do you want me to wait/not merge the PR in the meanwhile?

**Comment by BartGo** [comment]
Sorry to cut in.. but shutil.which() seems new in Python 3.3 - so it would break compatibility with Python 2.6, 2.7 and 3.2?....

**Comment by Lucas-C** [comment]
I'm going to use a backport for older versions of Python:
https://pypi.python.org/pypi/shutilwhich/
So no risk to break compatibility

@berderio: yes please wait a few more minutes :)

**Comment by Lucas-C** [comment]
Closing as #64 was merged
