### ISSUE TITLE
"pew new" fails on raspberry pi

### ISSUE THREAD

**Issue by AlbericC** [berdario/pew#65]
Hi, I tried to pip install pew on a rPi today, here is how it went. (raspbian, python3.2) 

````sh

$ sudo pip install pew
Collecting pew
  Using cached pew-0.1.14-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): virtualenv>=1.11 in /usr/local/lib/python3.2/dist-packages (from pew)
Requirement already satisfied (use --upgrade to upgrade): virtualenv-clone>=0.2.5 in /usr/local/lib/python3.2/dist-packages (from pew)
Requirement already satisfied (use --upgrade to upgrade): pathlib in /usr/local/lib/python3.2/dist-packages (from pew)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.8 in /usr/local/lib/python3.2/dist-packages (from pew)
Installing collected packages: pew
Successfully installed pew-0.1.14
 
$ pew new testpew
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python3.2/dist-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python3.2/dist-packages/pew/pew.py", line 283
    new_paths = [os.path.abspath(d) + u"\n" for d in args.dirs]
                                          ^
SyntaxError: invalid syntax
````

**Comment by berdario** [comment]
Thank you for the report

Python3.2 [isn't quite supported](https://github.com/berdario/pew/pull/42#issuecomment-67796094). It's been quite a while since I had a look at it, and it was a bit confusing the fact that we specify the dependencies for Py32 in the setup.py... but then we don't actually run tests against it (the latests versions of Ubuntu don't ship with Py32, so tests weren't run on it neither locally or on TravisCI)

[I enabled it](https://github.com/berdario/pew/commit/74d24a91c7d2b329888624722980e3d14519061d) and I'll see to get it working, now
