### ISSUE TITLE
Pew 0.1.16 crash on Windows (related to pythonz?)

### ISSUE THREAD

**Issue by BartGo** [berdario/pew#68]
Windows 7, Python 2.7.8, Git Bash.

pew 0.1.16 installed by pip (`pip install --upgrade pew`), crashes:

```
$ pew ls
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\pew.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pew\__init__.py", line 11, in <module>
    from . import pew
  File "c:\python27\lib\site-packages\pew\pew.py", line 21, in <module>
    from pythonz.commands.install import InstallCommand
  File "c:\python27\lib\site-packages\pythonz\commands\install.py", line 5, in <module>
    from pythonz.installer.pythoninstaller import PythonInstaller
  File "c:\python27\lib\site-packages\pythonz\installer\pythoninstaller.py", line 19, in <module>
    from pythonz.downloader import Downloader, DownloadError, validate_sha256
  File "c:\python27\lib\site-packages\pythonz\downloader.py", line 2, in <module>
    from mmap import mmap, PROT_READ
ImportError: cannot import name PROT_READ
```

The same with other commands (version, new, ...).

It works when downgraded to pew 0.1.15 through `pip install pew==0.1.15`.

**Comment by berdario** [comment]
Whoops

Yes, Pythonz is supported only on Linux+Macosx, and so when I wrote code to calculate the sha256 of a file, I didn't bother to make it compatible with Windows

If you want, there's already a workaround for that in master (I added it for a similar issue on CI)

Otherwise I'll release a new version soon (My plan was to wait for the changes in Pythonz to be merged, but I might hurry up another release before then)

**Comment by BartGo** [comment]
Yes, catch ImportError :)

**Comment by berdario** [comment]
Fixed in https://github.com/berdario/pew/commit/9e739606f563b0cdfe8f884815084fcd93e93109
