### ISSUE TITLE
Can't create virtualenv with Python 3.5.0

### ISSUE THREAD

**Issue by thuandt** [berdario/pew#73]
Currently, I'm using Ubuntu 15.10 with latest pew (0.1.18).
I'm install CPython 3.5.0 with pythonz and create virtualenv with Python 3.5.0 but it's raise this message

```bash
pew new --python=$(pythonz locate 3.5.0) mailman                                                                             
Running virtualenv with interpreter /home/mrtux/.pythonz/pythons/CPython-3.5.0/bin/python3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 371, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 23, in <module>
    import subprocess
  File "/home/mrtux/.pythonz/pythons/CPython-3.5.0/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/home/mrtux/.pythonz/pythons/CPython-3.5.0/lib/python3.5/signal.py", line 8, in <module>
    _IntEnum._convert(
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 373, in __getattr__
    raise AttributeError(name)
AttributeError: _convert
Error while trying to remove the /home/mrtux/DevProjects/virtualenvs/mailman env: 
No such file or directory
```

**Comment by berdario** [comment]
This seems to be a virtualenv issue:

https://github.com/pypa/virtualenv/issues/763

If you uninstall enum34 or you upgrade virtualenv to the latest development version, you shouldn't see the problem anymore
