### ISSUE TITLE
Non-ASCII chars in .bashrc crash pew

### ISSUE THREAD

**Issue by Zopieux** [berdario/pew#81]
My prompt (`PS1`) has fancy Unicode characters so pew crashes with `UnicodeEncodeError` when writing the temporary `.bashrc`.

On [this line](https://github.com/berdario/pew/blob/3cb002f3a18ce8399edab8b272c90f306ec30903/pew/pew.py#L150):
```python
        with NamedTemporaryFile('w+') as rcfile:
            with bashrcpath.open() as bashrc:
                rcfile.write(bashrc.read())  # crashes here
            rcfile.write('\nexport PATH=' + compute_path(env))
```
`rcfile` has a default encoding of `ascii` which cannot encode said characters for writing. Using byte strings everywhere might be the only right solution to this issue.

**Comment by jabbalaci** [comment]
Same problem here. In my `.bashrc` I had a non-Ascii character in a comment (`á`) and it produced a crash:

```
$ pew new mypew
Using base prefix '/usr'
New python executable in mypew/bin/python3
Also creating executable in mypew/bin/python
Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 684, in pew
    return command(sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 227, in new_cmd
    shell(args.envname)
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 172, in shell
    fork_bash(env, cwd)
  File "/usr/local/lib/python2.7/dist-packages/pew/pew.py", line 150, in fork_bash
    rcfile.write(bashrc.read())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 3908: ordinal not in range(128)
```

**Comment by berdario** [comment]
This was the same issue as #76

Thanks for the bug report

Should be fixed now, I'll release a new version on pypi
