### ISSUE TITLE
Error with sitepackages_dir and toggleglobalsitepackages

### ISSUE THREAD

**Issue by isbadawi** [berdario/pew#9]
I'm on OS X 10.9, with python installed via homebrew. Within a virtualenv, the `toggleglobalsitepackages` and `sitepackages_dir` commands give me this error:

```
isbadawi@astaire:~$ pew toggleglobalsitepackages
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'sysconfig'
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 9, in <module>
    load_entry_point('pew==0.1.6', 'console_scripts', 'pew')()
  File "/usr/local/lib/python2.7/site-packages/invewrapper/invewrapper.py", line 438, in pew
    return command()
  File "/usr/local/lib/python2.7/site-packages/invewrapper/invewrapper.py", line 300, in toggleglobalsitepackages_cmd
    site = sitepackages_dir()
  File "/usr/local/lib/python2.7/site-packages/invewrapper/invewrapper.py", line 245, in sitepackages_dir
    print(distutils.sysconfig.get_python_lib())'])
  File "/usr/local/lib/python2.7/site-packages/invewrapper/invewrapper.py", line 57, in shell
    return check_output(*args).decode(locale.getlocale()[1]).strip()
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['python', '-c', 'import distutils; print(distutils.sysconfig.get_python_lib())']' returned non-zero exit status 1
```

**Comment by AlJohri** [comment]
macOS starts all GUI shells as a login shell by default so this applies to both iTerm and Terminal. iTerm also allows one to configure it to start as a non-login shell but this is non-standard for macOS.
