### ISSUE TITLE
Creating new environment fails when .bashrc is not present

### ISSUE THREAD

**Issue by eyelidlessness** [berdario/pew#99]
- Python 3.5 (installed with Homebrew)
- Pew 0.1.19
- Mac OS X 10.11.3

Steps to reproduce:

1. `pew new ...`

Expected:

Environment is created.

Observed:

```
Traceback (most recent call last):
  File "/usr/local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/usr/local/lib/python3.5/site-packages/pew/pew.py", line 677, in pew
    first_run_setup()
  File "/usr/local/lib/python3.5/site-packages/pew/pew.py", line 641, in first_run_setup
    with rcpath.open('r+') as rcfile:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 1136, in open
    opener=self._opener)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 992, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/MYUSER/.bashrc'
```

**Comment by albertfilice** [comment]
I'm seeing this problem as well

**Comment by berdario** [comment]
Should be fixed now

Thanks for reporting the issue!
